export const categories = [
  "Child & Adolescent Psychiatry",
  "Adult Psychiatry",
  "Geriatric Psychiatry",
  "Addiction Psychiatry",
  "Anxiety & Stress Management",
  "Depression Treatment",
  "Bipolar Disorder Management",
  "Schizophrenia & Psychotic Disorders",
  "OCD (Obsessive-Compulsive Disorder)",
  "PTSD (Post-Traumatic Stress Disorder)",
  "Personality Disorders",
  "Marriage & Relationship Counseling",
  "Family Therapy",
  "Cognitive Behavioral Therapy (CBT)",
  "Dialectical Behavior Therapy (DBT)",
  "Grief & Loss Counseling",
  "Sleep Disorders",
  "Eating Disorders",
  "ADHD & Behavioral Issues",
  "Psychiatric Medication Management",
  "Mindfulness & Stress Reduction",
  "Telepsychiatry",
];
