// Add these arrays at the top of the file, after imports
export const countries = [
  {
    value: "India",
    label: "India",
  },
];

export const states = {
  India: [
    { value: "Andhra Pradesh", label: "Andhra Pradesh" },
    { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
    { value: "Assam", label: "Assam" },
    { value: "Bihar", label: "Bihar" },
    { value: "Chhattisgarh", label: "Chhattisgarh" },
    { value: "Goa", label: "Goa" },
    { value: "Gujarat", label: "Gujarat" },
    { value: "Haryana", label: "Haryana" },
    { value: "Himachal Pradesh", label: "Himachal Pradesh" },
    { value: "Jharkhand", label: "Jharkhand" },
    { value: "Karnataka", label: "Karnataka" },
    { value: "Kerala", label: "Kerala" },
    { value: "Madhya Pradesh", label: "Madhya Pradesh" },
    { value: "Maharashtra", label: "Maharashtra" },
    { value: "Manipur", label: "Manipur" },
    { value: "Meghalaya", label: "Meghalaya" },
    { value: "Mizoram", label: "Mizoram" },
    { value: "Nagaland", label: "Nagaland" },
    { value: "Odisha", label: "Odisha" },
    { value: "Punjab", label: "Punjab" },
    { value: "Rajasthan", label: "Rajasthan" },
    { value: "Sikkim", label: "Sikkim" },
    { value: "Tamil Nadu", label: "Tamil Nadu" },
    { value: "Telangana", label: "Telangana" },
    { value: "Tripura", label: "Tripura" },
    { value: "Uttar Pradesh", label: "Uttar Pradesh" },
    { value: "Uttarakhand", label: "Uttarakhand" },
    { value: "West Bengal", label: "West Bengal" },
    {
      value: "Andaman and Nicobar Islands",
      label: "Andaman and Nicobar Islands",
    },
    { value: "Chandigarh", label: "Chandigarh" },
    {
      value: "Dadra and Nagar Haveli and Daman and Diu",
      label: "Dadra and Nagar Haveli and Daman and Diu",
    },
    { value: "Delhi", label: "Delhi" },
    { value: "Jammu and Kashmir", label: "Jammu and Kashmir" },
    { value: "Ladakh", label: "Ladakh" },
    { value: "Lakshadweep", label: "Lakshadweep" },
    { value: "Puducherry", label: "Puducherry" },
  ],
};

export const cities = {
  "Andhra Pradesh": [
    { value: "Visakhapatnam", label: "Visakhapatnam" },
    { value: "Vijayawada", label: "Vijayawada" },
    { value: "Guntur", label: "Guntur" },
    { value: "Nellore", label: "Nellore" },
    { value: "Kurnool", label: "Kurnool" },
    { value: "Rajahmundry", label: "Rajahmundry" },
    { value: "Tirupati", label: "Tirupati" },
    { value: "Kakinada", label: "Kakinada" },
    { value: "Kadapa", label: "Kadapa" },
    { value: "Anantapur", label: "Anantapur" },
  ],
  "Arunachal Pradesh": [
    { value: "Itanagar", label: "Itanagar" },
    { value: "Naharlagun", label: "Naharlagun" },
    { value: "Pasighat", label: "Pasighat" },
    { value: "Namsai", label: "Namsai" },
    { value: "Tawang", label: "Tawang" },
    { value: "Bomdila", label: "Bomdila" },
    { value: "Ziro", label: "Ziro" },
    { value: "Roing", label: "Roing" },
    { value: "Tezu", label: "Tezu" },
    { value: "Aalo", label: "Aalo" },
  ],
  Assam: [
    { value: "Guwahati", label: "Guwahati" },
    { value: "Silchar", label: "Silchar" },
    { value: "Dibrugarh", label: "Dibrugarh" },
    { value: "Jorhat", label: "Jorhat" },
    { value: "Nagaon", label: "Nagaon" },
    { value: "Tinsukia", label: "Tinsukia" },
    { value: "Tezpur", label: "Tezpur" },
    { value: "Bongaigaon", label: "Bongaigaon" },
    { value: "Diphu", label: "Diphu" },
    { value: "North Lakhimpur", label: "North Lakhimpur" },
  ],
  Bihar: [
    { value: "Patna", label: "Patna" },
    { value: "Gaya", label: "Gaya" },
    { value: "Bhagalpur", label: "Bhagalpur" },
    { value: "Muzaffarpur", label: "Muzaffarpur" },
    { value: "Purnia", label: "Purnia" },
    { value: "Darbhanga", label: "Darbhanga" },
    { value: "Bihar Sharif", label: "Bihar Sharif" },
    { value: "Arrah", label: "Arrah" },
    { value: "Begusarai", label: "Begusarai" },
    { value: "Katihar", label: "Katihar" },
  ],
  Chhattisgarh: [
    { value: "Raipur", label: "Raipur" },
    { value: "Bhilai", label: "Bhilai" },
    { value: "Bilaspur", label: "Bilaspur" },
    { value: "Korba", label: "Korba" },
    { value: "Durg", label: "Durg" },
    { value: "Rajnandgaon", label: "Rajnandgaon" },
    { value: "Raigarh", label: "Raigarh" },
    { value: "Jagdalpur", label: "Jagdalpur" },
    { value: "Ambikapur", label: "Ambikapur" },
    { value: "Dhamtari", label: "Dhamtari" },
  ],
  Goa: [
    { value: "Panaji", label: "Panaji" },
    { value: "Vasco da Gama", label: "Vasco da Gama" },
    { value: "Margao", label: "Margao" },
    { value: "Mapusa", label: "Mapusa" },
    { value: "Ponda", label: "Ponda" },
    { value: "Bicholim", label: "Bicholim" },
    { value: "Curchorem", label: "Curchorem" },
    { value: "Cuncolim", label: "Cuncolim" },
    { value: "Valpoi", label: "Valpoi" },
    { value: "Sanquelim", label: "Sanquelim" },
  ],
  Gujarat: [
    { value: "Ahmedabad", label: "Ahmedabad" },
    { value: "Surat", label: "Surat" },
    { value: "Vadodara", label: "Vadodara" },
    { value: "Rajkot", label: "Rajkot" },
    { value: "Bhavnagar", label: "Bhavnagar" },
    { value: "Jamnagar", label: "Jamnagar" },
    { value: "Junagadh", label: "Junagadh" },
    { value: "Gandhinagar", label: "Gandhinagar" },
    { value: "Gandhidham", label: "Gandhidham" },
    { value: "Anand", label: "Anand" },
  ],
  Haryana: [
    { value: "Faridabad", label: "Faridabad" },
    { value: "Gurgaon", label: "Gurgaon" },
    { value: "Panipat", label: "Panipat" },
    { value: "Ambala", label: "Ambala" },
    { value: "Yamunanagar", label: "Yamunanagar" },
    { value: "Rohtak", label: "Rohtak" },
    { value: "Hisar", label: "Hisar" },
    { value: "Karnal", label: "Karnal" },
    { value: "Sonipat", label: "Sonipat" },
    { value: "Panchkula", label: "Panchkula" },
  ],
  "Himachal Pradesh": [
    { value: "Shimla", label: "Shimla" },
    { value: "Mandi", label: "Mandi" },
    { value: "Solan", label: "Solan" },
    { value: "Nahan", label: "Nahan" },
    { value: "Bilaspur", label: "Bilaspur" },
    { value: "Kullu", label: "Kullu" },
    { value: "Dharamshala", label: "Dharamshala" },
    { value: "Hamirpur", label: "Hamirpur" },
    { value: "Una", label: "Una" },
    { value: "Chamba", label: "Chamba" },
  ],
  Jharkhand: [
    { value: "Ranchi", label: "Ranchi" },
    { value: "Jamshedpur", label: "Jamshedpur" },
    { value: "Dhanbad", label: "Dhanbad" },
    { value: "Bokaro Steel City", label: "Bokaro Steel City" },
    { value: "Deoghar", label: "Deoghar" },
    { value: "Hazaribagh", label: "Hazaribagh" },
    { value: "Giridih", label: "Giridih" },
    { value: "Ramgarh", label: "Ramgarh" },
    { value: "Phusro", label: "Phusro" },
    { value: "Chirkunda", label: "Chirkunda" },
  ],
  Karnataka: [
    { value: "Bangalore", label: "Bangalore" },
    { value: "Mysore", label: "Mysore" },
    { value: "Hubli-Dharwad", label: "Hubli-Dharwad" },
    { value: "Mangalore", label: "Mangalore" },
    { value: "Belgaum", label: "Belgaum" },
    { value: "Gulbarga", label: "Gulbarga" },
    { value: "Davanagere", label: "Davanagere" },
    { value: "Bellary", label: "Bellary" },
    { value: "Bijapur", label: "Bijapur" },
    { value: "Shimoga", label: "Shimoga" },
  ],
  Kerala: [
    { value: "Thiruvananthapuram", label: "Thiruvananthapuram" },
    { value: "Kochi", label: "Kochi" },
    { value: "Kozhikode", label: "Kozhikode" },
    { value: "Thrissur", label: "Thrissur" },
    { value: "Kollam", label: "Kollam" },
    { value: "Palakkad", label: "Palakkad" },
    { value: "Alappuzha", label: "Alappuzha" },
    { value: "Kannur", label: "Kannur" },
    { value: "Kottayam", label: "Kottayam" },
    { value: "Malappuram", label: "Malappuram" },
  ],
  "Madhya Pradesh": [
    { value: "Indore", label: "Indore" },
    { value: "Bhopal", label: "Bhopal" },
    { value: "Jabalpur", label: "Jabalpur" },
    { value: "Gwalior", label: "Gwalior" },
    { value: "Ujjain", label: "Ujjain" },
    { value: "Sagar", label: "Sagar" },
    { value: "Dewas", label: "Dewas" },
    { value: "Satna", label: "Satna" },
    { value: "Ratlam", label: "Ratlam" },
    { value: "Rewa", label: "Rewa" },
  ],
  Maharashtra: [
    { value: "Mumbai", label: "Mumbai" },
    { value: "Pune", label: "Pune" },
    { value: "Nagpur", label: "Nagpur" },
    { value: "Thane", label: "Thane" },
    { value: "Nashik", label: "Nashik" },
    { value: "Aurangabad", label: "Aurangabad" },
    { value: "Solapur", label: "Solapur" },
    { value: "Kolhapur", label: "Kolhapur" },
    { value: "Amravati", label: "Amravati" },
    { value: "Nanded", label: "Nanded" },
  ],
  Manipur: [
    { value: "Imphal", label: "Imphal" },
    { value: "Thoubal", label: "Thoubal" },
    { value: "Kakching", label: "Kakching" },
    { value: "Ukhrul", label: "Ukhrul" },
    { value: "Churachandpur", label: "Churachandpur" },
    { value: "Bishnupur", label: "Bishnupur" },
    { value: "Senapati", label: "Senapati" },
    { value: "Jiribam", label: "Jiribam" },
    { value: "Moreh", label: "Moreh" },
    { value: "Lilong", label: "Lilong" },
  ],
  Meghalaya: [
    { value: "Shillong", label: "Shillong" },
    { value: "Tura", label: "Tura" },
    { value: "Nongstoin", label: "Nongstoin" },
    { value: "Jowai", label: "Jowai" },
    { value: "Baghmara", label: "Baghmara" },
    { value: "Resubelpara", label: "Resubelpara" },
    { value: "Williamnagar", label: "Williamnagar" },
    { value: "Nongpoh", label: "Nongpoh" },
    { value: "Madanrting", label: "Madanrting" },
    { value: "Mawlai", label: "Mawlai" },
  ],
  Mizoram: [
    { value: "Aizawl", label: "Aizawl" },
    { value: "Lunglei", label: "Lunglei" },
    { value: "Saiha", label: "Saiha" },
    { value: "Champhai", label: "Champhai" },
    { value: "Kolasib", label: "Kolasib" },
    { value: "Serchhip", label: "Serchhip" },
    { value: "Lawngtlai", label: "Lawngtlai" },
    { value: "Mamit", label: "Mamit" },
    { value: "Khawzawl", label: "Khawzawl" },
    { value: "Saitual", label: "Saitual" },
  ],
  Nagaland: [
    { value: "Kohima", label: "Kohima" },
    { value: "Dimapur", label: "Dimapur" },
    { value: "Mokokchung", label: "Mokokchung" },
    { value: "Tuensang", label: "Tuensang" },
    { value: "Wokha", label: "Wokha" },
    { value: "Zunheboto", label: "Zunheboto" },
    { value: "Mon", label: "Mon" },
    { value: "Phek", label: "Phek" },
    { value: "Kiphire", label: "Kiphire" },
    { value: "Longleng", label: "Longleng" },
  ],
  Odisha: [
    { value: "Bhubaneswar", label: "Bhubaneswar" },
    { value: "Cuttack", label: "Cuttack" },
    { value: "Rourkela", label: "Rourkela" },
    { value: "Berhampur", label: "Berhampur" },
    { value: "Sambalpur", label: "Sambalpur" },
    { value: "Puri", label: "Puri" },
    { value: "Balasore", label: "Balasore" },
    { value: "Bhadrak", label: "Bhadrak" },
    { value: "Baripada", label: "Baripada" },
    { value: "Jharsuguda", label: "Jharsuguda" },
  ],
  Punjab: [
    { value: "Ludhiana", label: "Ludhiana" },
    { value: "Amritsar", label: "Amritsar" },
    { value: "Jalandhar", label: "Jalandhar" },
    { value: "Patiala", label: "Patiala" },
    { value: "Bathinda", label: "Bathinda" },
    { value: "Mohali", label: "Mohali" },
    { value: "Pathankot", label: "Pathankot" },
    { value: "Hoshiarpur", label: "Hoshiarpur" },
    { value: "Batala", label: "Batala" },
    { value: "Moga", label: "Moga" },
  ],
  Rajasthan: [
    { value: "Jaipur", label: "Jaipur" },
    { value: "Jodhpur", label: "Jodhpur" },
    { value: "Kota", label: "Kota" },
    { value: "Bikaner", label: "Bikaner" },
    { value: "Ajmer", label: "Ajmer" },
    { value: "Udaipur", label: "Udaipur" },
    { value: "Bhilwara", label: "Bhilwara" },
    { value: "Alwar", label: "Alwar" },
    { value: "Sikar", label: "Sikar" },
    { value: "Pali", label: "Pali" },
  ],
  Sikkim: [
    { value: "Gangtok", label: "Gangtok" },
    { value: "Namchi", label: "Namchi" },
    { value: "Gyalshing", label: "Gyalshing" },
    { value: "Mangan", label: "Mangan" },
    { value: "Rangpo", label: "Rangpo" },
    { value: "Singtam", label: "Singtam" },
    { value: "Jorethang", label: "Jorethang" },
    { value: "Nayabazar", label: "Nayabazar" },
    { value: "Rongli", label: "Rongli" },
    { value: "Ravangla", label: "Ravangla" },
  ],
  "Tamil Nadu": [
    { value: "Chennai", label: "Chennai" },
    { value: "Coimbatore", label: "Coimbatore" },
    { value: "Madurai", label: "Madurai" },
    { value: "Tiruchirappalli", label: "Tiruchirappalli" },
    { value: "Salem", label: "Salem" },
    { value: "Tirunelveli", label: "Tirunelveli" },
    { value: "Tiruppur", label: "Tiruppur" },
    { value: "Vellore", label: "Vellore" },
    { value: "Erode", label: "Erode" },
    { value: "Thoothukkudi", label: "Thoothukkudi" },
  ],
  Telangana: [
    { value: "Hyderabad", label: "Hyderabad" },
    { value: "Warangal", label: "Warangal" },
    { value: "Nizamabad", label: "Nizamabad" },
    { value: "Karimnagar", label: "Karimnagar" },
    { value: "Ramagundam", label: "Ramagundam" },
    { value: "Khammam", label: "Khammam" },
    { value: "Mahbubnagar", label: "Mahbubnagar" },
    { value: "Nalgonda", label: "Nalgonda" },
    { value: "Adilabad", label: "Adilabad" },
    { value: "Suryapet", label: "Suryapet" },
  ],
  Tripura: [
    { value: "Agartala", label: "Agartala" },
    { value: "Udaipur", label: "Udaipur" },
    { value: "Dharmanagar", label: "Dharmanagar" },
    { value: "Kailasahar", label: "Kailasahar" },
    { value: "Belonia", label: "Belonia" },
    { value: "Ambassa", label: "Ambassa" },
    { value: "Khowai", label: "Khowai" },
    { value: "Teliamura", label: "Teliamura" },
    { value: "Sabroom", label: "Sabroom" },
    { value: "Santir Bazar", label: "Santir Bazar" },
  ],
  "Uttar Pradesh": [
    { value: "Lucknow", label: "Lucknow" },
    { value: "Kanpur", label: "Kanpur" },
    { value: "Ghaziabad", label: "Ghaziabad" },
    { value: "Agra", label: "Agra" },
    { value: "Meerut", label: "Meerut" },
    { value: "Varanasi", label: "Varanasi" },
    { value: "Allahabad", label: "Allahabad" },
    { value: "Bareilly", label: "Bareilly" },
    { value: "Aligarh", label: "Aligarh" },
    { value: "Moradabad", label: "Moradabad" },
  ],
  Uttarakhand: [
    { value: "Dehradun", label: "Dehradun" },
    { value: "Haridwar", label: "Haridwar" },
    { value: "Roorkee", label: "Roorkee" },
    { value: "Haldwani", label: "Haldwani" },
    { value: "Rudrapur", label: "Rudrapur" },
    { value: "Kashipur", label: "Kashipur" },
    { value: "Rishikesh", label: "Rishikesh" },
    { value: "Pithoragarh", label: "Pithoragarh" },
    { value: "Ramnagar", label: "Ramnagar" },
    { value: "Kichha", label: "Kichha" },
  ],
  "West Bengal": [
    { value: "Kolkata", label: "Kolkata" },
    { value: "Howrah", label: "Howrah" },
    { value: "Durgapur", label: "Durgapur" },
    { value: "Asansol", label: "Asansol" },
    { value: "Siliguri", label: "Siliguri" },
    { value: "Bardhaman", label: "Bardhaman" },
    { value: "Malda", label: "Malda" },
    { value: "Baharampur", label: "Baharampur" },
    { value: "Habra", label: "Habra" },
    { value: "Kharagpur", label: "Kharagpur" },
  ],
  "Andaman and Nicobar Islands": [
    { value: "Port Blair", label: "Port Blair" },
    { value: "Mayabunder", label: "Mayabunder" },
    { value: "Diglipur", label: "Diglipur" },
    { value: "Car Nicobar", label: "Car Nicobar" },
    { value: "Rangat", label: "Rangat" },
    { value: "Havelock Island", label: "Havelock Island" },
    { value: "Little Andaman", label: "Little Andaman" },
    { value: "Neil Island", label: "Neil Island" },
    { value: "Kamorta", label: "Kamorta" },
    { value: "Katchal", label: "Katchal" },
  ],
  Chandigarh: [
    { value: "Chandigarh", label: "Chandigarh" },
    { value: "Mani Majra", label: "Mani Majra" },
    { value: "Burail", label: "Burail" },
    { value: "Attawa", label: "Attawa" },
    { value: "Badheri", label: "Badheri" },
    { value: "Behlana", label: "Behlana" },
    { value: "Dadu Majra", label: "Dadu Majra" },
    { value: "Dhanas", label: "Dhanas" },
    { value: "Daria", label: "Daria" },
    { value: "Grain Market", label: "Grain Market" },
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    { value: "Daman", label: "Daman" },
    { value: "Diu", label: "Diu" },
    { value: "Silvassa", label: "Silvassa" },
    { value: "Amli", label: "Amli" },
    { value: "Vapi", label: "Vapi" },
    { value: "Dunetha", label: "Dunetha" },
    { value: "Kachigam", label: "Kachigam" },
    { value: "Dabhel", label: "Dabhel" },
    { value: "Bhimpore", label: "Bhimpore" },
    { value: "Nani Daman", label: "Nani Daman" },
  ],
  Delhi: [
    { value: "New Delhi", label: "New Delhi" },
    { value: "North Delhi", label: "North Delhi" },
    { value: "South Delhi", label: "South Delhi" },
    { value: "East Delhi", label: "East Delhi" },
    { value: "West Delhi", label: "West Delhi" },
    { value: "Central Delhi", label: "Central Delhi" },
    { value: "North East Delhi", label: "North East Delhi" },
    { value: "South West Delhi", label: "South West Delhi" },
    { value: "North West Delhi", label: "North West Delhi" },
    { value: "Shahdara", label: "Shahdara" },
  ],
  "Jammu and Kashmir": [
    { value: "Srinagar", label: "Srinagar" },
    { value: "Jammu", label: "Jammu" },
    { value: "Anantnag", label: "Anantnag" },
    { value: "Baramulla", label: "Baramulla" },
    { value: "Udhampur", label: "Udhampur" },
    { value: "Kathua", label: "Kathua" },
    { value: "Sopore", label: "Sopore" },
    { value: "Kupwara", label: "Kupwara" },
    { value: "Pulwama", label: "Pulwama" },
    { value: "Bijbehara", label: "Bijbehara" },
  ],
  Ladakh: [
    { value: "Leh", label: "Leh" },
    { value: "Kargil", label: "Kargil" },
    { value: "Diskit", label: "Diskit" },
    { value: "Khalsi", label: "Khalsi" },
    { value: "Khaltse", label: "Khaltse" },
    { value: "Nubra", label: "Nubra" },
    { value: "Zanskar", label: "Zanskar" },
    { value: "Drass", label: "Drass" },
    { value: "Padum", label: "Padum" },
    { value: "Nyoma", label: "Nyoma" },
  ],
  Lakshadweep: [
    { value: "Kavaratti", label: "Kavaratti" },
    { value: "Agatti", label: "Agatti" },
    { value: "Amini", label: "Amini" },
    { value: "Andrott", label: "Andrott" },
    { value: "Kalpeni", label: "Kalpeni" },
    { value: "Kiltan", label: "Kiltan" },
    { value: "Chetlat", label: "Chetlat" },
    { value: "Kadmat", label: "Kadmat" },
    { value: "Bitra", label: "Bitra" },
    { value: "Minicoy", label: "Minicoy" },
  ],
  Puducherry: [
    { value: "Puducherry", label: "Puducherry" },
    { value: "Karaikal", label: "Karaikal" },
    { value: "Yanam", label: "Yanam" },
    { value: "Mahe", label: "Mahe" },
    { value: "Ozhukarai", label: "Ozhukarai" },
    { value: "Villianur", label: "Villianur" },
    { value: "Ariyankuppam", label: "Ariyankuppam" },
    { value: "Bahour", label: "Bahour" },
    { value: "Mannadipet", label: "Mannadipet" },
    { value: "Nettapakkam", label: "Nettapakkam" },
  ],
};
